name: cavity3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  image: ^3.0.2
  image_picker: ^0.8.6
  tflite_flutter: ^0.9.0
  tflite_flutter_helper:
    git:
      url: https://github.com/filofan1/tflite_flutter_helper.git
      ref: 783f15e5a87126159147d8ea30b98eea9207ac70

  go_router: ^13.0.0
  flutter_svg: ^2.0.9
  provider: ^6.1.1
  
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_ui_auth: ^1.14.0
  cloud_functions: ^4.6.5
  firebase_database: ^10.4.9

  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  intl: ^0.18.1
  bottom_picker: ^2.7.0
  pdf: ^3.8.4
  printing: ^5.3.0
  firebase_ui_oauth_google: ^1.3.2
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  fonts:
    - family: SquadaOne
      fonts:
        - asset: assets/SquadaOne-Regular.ttf
    - family: ContrailOne
      fonts:
        - asset: assets/ContrailOne-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/Roboto-Light.ttf
  
  assets:
    - assets/
    - assets/images/
    - assets/svg/
